language: node_js
node_js:
  - '10'
script:
  - npm run lint
  - npm run build
  - istanbul cover node_modules/mocha/bin/_mocha ./test/**/*.js -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
