language: node_js
node_js:
- '10'
script:
- npm run lint
- npm run build
- istanbul cover node_modules/mocha/bin/_mocha ./test/**/*.js -- -R spec
before_script:
- npm install codeclimate-test-reporter istanbul -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: heroku
  app: gregbiv
  run:
  - npx sequelize-cli db:migrate
  api_key:
    secure: OyBLvyQyJ55mckWROWIDtisYyxHjAG8SIrMZg1sVyzFh7n0XSRe3EeDqMlygHJRBTzjPnACbTObzTLijHfLZfxogQuiBTjV2EfSZOro8zOCKhIpiQZ4BzzK3f8KkxUdRVfmeHLXgNoTqLSRHp8hX/Yn6EkSR3t5PnbU8OictflwUdLum+whuexOIXV2hNWYAWlSH5uL8p9pLoqpe752FvbyW1Nb6SxXt55OVDs8vMx/DsWNlUfEiKJNRy+PJ5MTnnndYvzXHIqv6qj2PW9bkQBfhuR//yB5Q4kfu8IJA5WkyxoUVFjKilCYS8oImpFngSd3g1lDXSV9t1Dt057DvY/Kgd7qVKXMGaj/EeVA92Y8ZK7Atrr3IQdFXgl6pfe0ZESwouflAgPLqpZhlqNP18uwVk1HGvW9lYooQtV0A8exncwjR3rzyDWwQZsrmO7B9cmaoZgct7zI9JKL6dj/TF1ll+jao/6wFys0+mirGeml1ByvvIpxfujWXvd2A+N5sAsmzhGbl6St2DaLbVHlkZboLXwwWq8Zt8+rmfXWentFzUws5SfYB0+sMMSJsY0D8Kiu4Li7/7XfByNsQW+N+ei2uW1hOy1heUsI6BCTD4LGDAnJgyLdRt0PXkzjJRWaSseheSHAZ/felFvhTVU0TBjcOXSl73wEPJwX/xwR5TIo=
