language: node_js
node_js:
  - '10'
services:
  - postgresql
env:
  global:
  - NODE_ENV=test
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test-unit
  - npm run test-integration
before_script:
  - psql -c 'create database db_test;' -U postgres
  - psql -c "CREATE USER user_test WITH PASSWORD null;" -U postgres
  - npm start&
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - npm run codeclimate-coverage
