version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 8080
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_NAME: db
      DB_HOST: postgres
      DB_DIALECT: postgres
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
